## Basic Configuration

baseurl = "https://chrigl.dev"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Christoph Glaubitz"
title = "Christoph Glaubitz"

theme = "hugo-goa"

## Hugo Built-in Features
enableRobotsTXT = true

## Site Settings
[params]
author = "Christoph Glaubitz"
intro = ""
description = "cyclist, runner, doing computer stuff for living"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Christoph Glaubitz"
keywords = "minimalist,blog,gopher,go,python,kubernetes,openstack,developer"

## Social Accounts
[params.social]
github = "chrigl"
xing = "Christoph_Glaubitz"
linkedin = "chrigl"
email = "chris@glaubitz.berlin"

## Extras
[params.extra]
copyright = "© 2023. Christoph Glaubitz. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
